site_name: Termux Docs

theme:
  features:
    - navigation.instant
  font:
    text: Noto Sans SC
  logo: images/terminal.svg
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: zh
    
repo_url: https://github.com/tennousuathena/termux.in

repo_name: tennousuathena/termux.in

plugins:
  - git-revision-date-localized:
      type: iso_date

copyright: 本站内容采用<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">知识共享署名-相同方式共享 4.0 国际许可协议</a>进行许可。

extra:
  alternate:
    - name: 简体中文
      link: /
      lang: zh

    # - name: 繁體中文
    #   link: /zh-Hant
    #   lang: zh-Hant

    # - name: English
    #   link: /en
    #   lang: en



  generator: false